### ISSUE TITLE
Remove globals and/or

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/Landing-page-v2.0#1]
https://github.com/nexlabs22/Landing-page-v2.0/blob/61915f803e830bb26dd439b6e4133847529c5d59/src/styles/globals.css#L9-L16
Can you remove the globals.css or leave it empty?

**Comment by MedNewton** [comment]
empty for the moment : 
https://github.com/nexlabs22/Landing-page-v2.0/commit/4a7a6e43a7737a3b7f1543fb656bfbc81677dacf

**Comment by MedNewton** [comment]
removed. here : 
https://github.com/nexlabs22/Landing-page-v2.0/commit/97200e1c4fc973617a500ded6aaee8ae43d2c483
