### ISSUE TITLE
Remove duplicates

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/Landing-page-v2.0#4]
https://github.com/nexlabs22/Landing-page-v2.0/blob/b72d6c8a004bbee18668664e71bcdde0c4185d47/src/app/components/LineChart.tsx#L58-L62

**Comment by MedNewton** [comment]
done. Here : 
https://github.com/nexlabs22/Landing-page-v2.0/commit/b7d701b2aa63640799075e120feb61fbdadf7714
