### ISSUE TITLE
Review code 12 nov

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/Landing-page-v2.0#5]
The Sections map is written with capital, changing case is not easy (because of the caching), any reason make this one capital and the rest smaller case (I prefer smaller case everywhere).

https://github.com/nexlabs22/Landing-page-v2.0/blob/515080e775aef5b4835c669f6d54b7ab4d8d358e/src/app/Sections/Bento.tsx#L43-L60
You can do the conditinional render directly in the image, no stack needed.

https://github.com/nexlabs22/Landing-page-v2.0/blob/515080e775aef5b4835c669f6d54b7ab4d8d358e/src/app/Sections/Bento.tsx#L14
Some stacks can be replace with <Box> if they only wrap one component, it should not be stack. 

https://github.com/nexlabs22/Landing-page-v2.0/blob/515080e775aef5b4835c669f6d54b7ab4d8d358e/src/app/Sections/Conversion.tsx#L24
-> not a stack and you can put the display logic inside the <Image> props itself I think

https://github.com/nexlabs22/Landing-page-v2.0/blob/515080e775aef5b4835c669f6d54b7ab4d8d358e/src/app/Sections/Conversion.tsx#L9
-> box

https://github.com/nexlabs22/Landing-page-v2.0/blob/515080e775aef5b4835c669f6d54b7ab4d8d358e/src/app/Sections/Faq.tsx#L7
-> please remove unused imports

https://github.com/nexlabs22/Landing-page-v2.0/blob/515080e775aef5b4835c669f6d54b7ab4d8d358e/src/app/Sections/Faq.tsx#L16
-> why not just one accordion?

https://github.com/nexlabs22/Landing-page-v2.0/blob/515080e775aef5b4835c669f6d54b7ab4d8d358e/src/app/Sections/Partners.tsx#L16-L20
-> Try to find all instances where a Stack has 1 or less childs, then its a Box.

https://github.com/nexlabs22/Landing-page-v2.0/blob/515080e775aef5b4835c669f6d54b7ab4d8d358e/src/app/Sections/Partners.tsx#L25
no need to duplicate
loop=0  === infinite loop
https://www.npmjs.com/package/react-fast-marquee

https://github.com/nexlabs22/Landing-page-v2.0/blob/515080e775aef5b4835c669f6d54b7ab4d8d358e/src/app/components/ChartCard.tsx#L21
Please remove excess whitespaces

https://github.com/nexlabs22/Landing-page-v2.0/blob/515080e775aef5b4835c669f6d54b7ab4d8d358e/src/app/components/ChartCard.tsx#L20
Please check if you can add the preferential usage of arrow function rather than React.FC to the AI default instructions.

https://github.com/nexlabs22/Landing-page-v2.0/blob/515080e775aef5b4835c669f6d54b7ab4d8d358e/src/app/components/ChartCard.tsx#L41-L43
All charts and images please self-closing. 
This Stack -> Box

https://github.com/nexlabs22/Landing-page-v2.0/blob/515080e775aef5b4835c669f6d54b7ab4d8d358e/src/app/components/CustomCard.tsx#L2
unused import, you should be able to find and delete them all with: ctrl +. per file.

src/app/components/DottedBackground.tsx
-> slows down the browser because each one is an element, please f.e. create a pattern (like a row) and loop over it, 
or create an image of a section and repeat those.

https://github.com/nexlabs22/Landing-page-v2.0/blob/515080e775aef5b4835c669f6d54b7ab4d8d358e/src/app/components/FooterShadows.tsx#L7
https://github.com/nexlabs22/Landing-page-v2.0/blob/515080e775aef5b4835c669f6d54b7ab4d8d358e/src/app/components/HeroShadows.tsx#L10
-> selfclosing

https://github.com/nexlabs22/Landing-page-v2.0/blob/515080e775aef5b4835c669f6d54b7ab4d8d358e/src/app/components/LineChart.tsx#L6
unused imports

src/app/theme/theme.d.ts
we use this file?

https://github.com/nexlabs22/Landing-page-v2.0/blob/515080e775aef5b4835c669f6d54b7ab4d8d358e/src/app/theme/theme.ts#L103-L137
please lower for higher tags, the lack of contrast we are seeing is because the standards texts are emphasized.
And wrt. to the breakpoints, those are just default.

https://github.com/nexlabs22/Landing-page-v2.0/blob/515080e775aef5b4835c669f6d54b7ab4d8d358e/src/app/theme/theme.ts#L64
why does every contrastText need to be overwritten, just pick one if you need white? 

https://github.com/nexlabs22/Landing-page-v2.0/blob/515080e775aef5b4835c669f6d54b7ab4d8d358e/src/app/Articles.ts#L43-L47
We have some articles in MGS related to Nexlabs that I would like here instead of these duplicates. We have 
a category 'Nexlabs protocol'

![image](https://github.com/user-attachments/assets/116bc790-cb1c-4561-ac9f-46ca858a1478)

https://github.com/nexlabs22/Landing-page-v2.0/blob/515080e775aef5b4835c669f6d54b7ab4d8d358e/tsconfig.json#L29-L34
this should be same:
"@*/*": ["src/*/*"]

**Comment by MedNewton** [comment]
> You can do the conditinional render directly in the image, no stack needed.

Normally a Stack is a div, but only if it is empty (like a shadow div or a dot shape) then it is replaced by Box. This is done: 
https://github.com/nexlabs22/Landing-page-v2.0/commit/8393eb16a76b74531b8a83778540c7bf6b3b11f0

**Comment by MedNewton** [comment]
> The Sections map is written with capital, changing case is not easy (because of the caching), any reason make this one capital and the rest smaller case (I prefer smaller case everywhere).

Fixed : 
https://github.com/nexlabs22/Landing-page-v2.0/commit/8393eb16a76b74531b8a83778540c7bf6b3b11f0

**Comment by MedNewton** [comment]
> -> selfclosing

All empty boxes are now self closing : 
https://github.com/nexlabs22/Landing-page-v2.0/commit/35e0638f828ad7c53a2b9690b9423c52b874057e

**Comment by MedNewton** [comment]
-> not a stack and you can put the display logic inside the  props itself I think

No actually we can not: the nextjs Image tag can have the display property, but it can not be seperated by screen size (you can NOT have xs or lg inside it), this is why I put it in a stack because I need to make it not displayed for some screen size.

**Comment by MedNewton** [comment]
> -> please remove unused imports

Removed all unused import in the repo : 
https://github.com/nexlabs22/Landing-page-v2.0/commit/7c325caf193d096f8a851bbc1ff3f5ebad1f2fdc

**Comment by MedNewton** [comment]
> -> why not just one accordion?

One accordion is just one box that opens and closes, this is how it is made by MUI.

**Comment by MedNewton** [comment]
> no need to duplicate
> loop=0 === infinite loop
> https://www.npmjs.com/package/react-fast-marquee

it is not about the loop. even without that peoperty the marquee will be infinite. It is about the look of it : 
We have few elements, and they are small in size, and even all 5 of them does not cover the width of the page, so when the loop gets to the last element, there will be a big blank gap visible before the first element comes into viewport again.

**Comment by MedNewton** [comment]
> All charts and images please self-closing.

done : 
https://github.com/nexlabs22/Landing-page-v2.0/commit/970abdf8eedb657c9f9afc33de35dd87482690e7

https://github.com/nexlabs22/Landing-page-v2.0/commit/ec4bf89bb903443084b017193f32f356ef5770ec

**Comment by MedNewton** [comment]
> why does every contrastText need to be overwritten, just pick one if you need white?

cleaned the theme, remove repeated contrast values and breakpoints : 
https://github.com/nexlabs22/Landing-page-v2.0/commit/07bade0d0e806584a6e3d9e5d8830b79ac523ef5

**Comment by MedNewton** [comment]
> We have some articles in MGS related to Nexlabs that I would like here instead of these duplicates. We have
> a category 'Nexlabs protocol'

Done. Added new artocles and removed duplicates : 
https://github.com/nexlabs22/Landing-page-v2.0/commit/414b30d62ace45d71e4c506e92bf23d77a3c27f5

**Comment by MedNewton** [comment]
> this should be same:
> "@_/_": ["src/_/_"]

fixed. moved assets inside app folder and unified the aliases : 
https://github.com/nexlabs22/Landing-page-v2.0/commit/017582341d601444a0b29dbb45ae91a285337748

**Comment by MedNewton** [comment]
removed the following unused packages : 
- env.js
- zod
- geist

added the 'sharp' package, recommended for image optimization by Nextjs.

https://github.com/nexlabs22/Landing-page-v2.0/commit/927b332c953dcceb29c1bcc32d8485fdca2d893c

**Comment by Waltermelon-lang** [comment]
> > You can do the conditinional render directly in the image, no stack needed.
> 
> Normally a Stack is a div, but only if it is empty (like a shadow div or a dot shape) then it is replaced by Box. This is done: [8393eb1](https://github.com/nexlabs22/Landing-page-v2.0/commit/8393eb16a76b74531b8a83778540c7bf6b3b11f0)

Please check my image and then reply to the comment. 
https://github.com/nexlabs22/Landing-page-v2.0/blob/515080e775aef5b4835c669f6d54b7ab4d8d358e/src/app/Sections/Bento.tsx#L43
Remove the conditional rendering from the Stack and put in image itself

**Comment by Waltermelon-lang** [comment]
> > this should be same:
> > "@_/_": ["src/_/_"]
> 
> fixed. moved assets inside app folder and unified the aliases : [0175823](https://github.com/nexlabs22/Landing-page-v2.0/commit/017582341d601444a0b29dbb45ae91a285337748)

I just meant that I think you can make the @ aliases easier by creating a generic relative import for all files in the src directory.

**Comment by Waltermelon-lang** [comment]
> > > this should be same:
> > > "@_/_": ["src/_/_"]
> > 
> > 
> > fixed. moved assets inside app folder and unified the aliases : [0175823](https://github.com/nexlabs22/Landing-page-v2.0/commit/017582341d601444a0b29dbb45ae91a285337748)
> 
> I just meant that I think you can make the @ aliases easier by creating a generic relative import for all files in the src directory.
