### ISSUE TITLE
fontweight bring balance

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/Landing-page-v2.0#6]
https://github.com/nexlabs22/Landing-page-v2.0/blob/3d33001384502eb7fb1cc8431a15ac76cf7467d4/src/app/theme/theme.ts#L97-L114

I understand that increasing the fontweight looks good for titles, but I would like to retain the 
gradiation from low to heigh font weight in order to emphasise titles but not have every text too bold. 
Currently, the body/standard texts IMO are overly bold and are asking to much attention from the viewer. 

example suggestion: 

const typography = {
  h1: {
    fontWeight: 700, // Bold for primary emphasis on the largest heading
  },
  h2: {
    fontWeight: 600, // Semi-Bold for strong emphasis but less than h1
  },
  h3: {
    fontWeight: 600, // Consistent Semi-Bold for medium emphasis
  },
  h4: {
    fontWeight: 500, // Medium weight for smaller headings
  },
  h5: {
    fontWeight: 500, // Medium weight for subtle section headings
  },
  h6: {
    fontWeight: 500, // Medium weight for minor headers
  },
  subtitle1: {
    fontWeight: 400, // Normal for readable subtitles
  },
  subtitle2: {
    fontWeight: 500, // Medium to differentiate from subtitle1
  },
  body1: {
    fontWeight: 400, // Normal for primary body text
  },
  body2: {
    fontWeight: 400, // Normal for secondary text
  },
  button: {
    fontWeight: 500, // Medium for slightly emphasized action text
  },
  caption: {
    fontWeight: 400, // Normal for small annotations
  },
  overline: {
    fontWeight: 600, // Semi-Bold to make small labels stand out
  },
}

**Comment by MedNewton** [comment]
Tested it here : 
https://github.com/nexlabs22/Landing-page-v2.0/commit/96191583815392129a7f81f32b33c7d9a450e517
