### ISSUE TITLE
Individual Component renders can be reduced by combining (or replace)

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/Landing-page-v2.0#7]
https://github.com/nexlabs22/Landing-page-v2.0/blob/3d33001384502eb7fb1cc8431a15ac76cf7467d4/src/app/components/DottedBackground.tsx#L19

**Comment by MedNewton** [comment]
Done. Here : 
https://github.com/nexlabs22/Landing-page-v2.0/commit/c89732e8a208e60c00b736d888e033a3b3dcd9f0
